### ISSUE TITLE
Use different JSON serializer

### ISSUE THREAD

**Issue by bbarberBPL** [boston-library/curator#10]
Since `active_model_serializer` is in a questionable state right now we will probably need to switch off that gem and use something else.  The most recommended serializer is `fast-jsonapi`. Unfortunatley it does not allow us to use the json schema we have come up with since it uses the JSONAPIschema instead of just JSON. The options we have are 

`jbuilder`
`blueprinter`
`rabl`

I recommend we go with `blueprinter` since rewriting the code should be minimal since it works the same way as AMS. If we go with `jbuilder` or `rabl` though we need to rewrite the code in the view layer.

**Comment by bbarberBPL** [comment]
I Update so tried using `blueprinter` and while it was pretty flexible it wasn't working with associations for some reason. I also tried implementing `rabl` but felt it was a little too complicated plus it would require a heavy rework by transitioning to views. I'm thinking we need to make another gem that has the following functionality.

1. Ability to define `serializers` in the same manner as `AMS` and `blueprinter`.
2. Ability to support multiple formats `xml` and `json` being the first milestone. 
3. Ability to render quickly using the `oj` gem for `json` and the `ox` gem for `xml`
4. Ability to cache in the same manner as `AMS`

**Comment by ebenenglish** [comment]
Fixed via #54
