### ISSUE TITLE
Implement Acts as State Machine(aasm)

### ISSUE THREAD

**Issue by bbarberBPL** [boston-library/curator#13]
Added this mainly for controlling the states between `enums` on the `metastreams -> workflow` model. As we can use this to fire callbacks between states for logging or triggering background jobs(like derivatives processing). It also does't require an ORM to use so we may be able to use it with any old model we define a state in. Will add more details as scope is better defined for this. 

[AASM Readme](https://github.com/aasm/aasm/blob/master/README.md)

**Comment by ebenenglish** [comment]
Fixed via #107
