### ISSUE TITLE
Add solr wrapper to rake file and wrap spec task 

### ISSUE THREAD

**Issue by bbarberBPL** [boston-library/curator#20]
Following the guide for [solr_wrapper](https://github.com/cbeer/solr_wrapper)
 And the following code snippets for starting a task within the solr wrapper block

[Here(ignore fc repo part)](https://github.com/samvera/active_fedora/blob/c1d213121bb6fcc7f7c888391a310f13075b08bf/lib/active_fedora/rake_support.rb#L7)

And [Here](https://github.com/samvera/active_fedora/blob/c1d213121bb6fcc7f7c888391a310f13075b08bf/lib/tasks/active_fedora_dev.rake#L63)
 
basically in this part of the [Rakefile](https://github.com/boston-library/curator/blob/954096675ed76f1bba02cf76e752be9a4a152956/Rakefile#L25)

to pseudo code it should be something like this 

```
RSpec::Core::RakeTask.new(:spec)
...
task :rspec do
    SolrWrapper.wrap([config stuff]) do |solr|
        solr.with_collection([collection config] do
               Rake::Task['spec'].invoke
           end
    end
end
```
We should probably set this up in a way that will be able to handle CI testing in the future. And possibly move some of the task declarations to the curator_tasks.rake file under a nested namespace. Similar to how `active_fedora` has there tests defined in their lib/tasks.

**Comment by ebenenglish** [comment]
Fixed via #24
