### ISSUE TITLE
invalid identifiers not being indexed properly

### ISSUE THREAD

**Issue by ebenenglish** [boston-library/curator#209]
In `IdentifierIndexer`, identifier objects where `invalid: true` are not being indexed correctly.

The check on L31 uses `if identifier.invalid?`, which is actually calling the `ActiveModel::Validations#invalid?` method rather than checking the value of the `invalid` attribute.

Change this to `if identifier.invalid`

One this is deployed, we will need to reindex any record that has an invalid identifier.

Also see if we can update the specs to make sure this doesn't get messed up in the future.

**Comment by bbarberBPL** [comment]
Closed via #211
