### ISSUE TITLE
MinterService should retrieve ARK from ark-manager

### ISSUE THREAD

**Issue by ebenenglish** [boston-library/curator#39]
To create unique persistent identifiers, `MinterService` (app/services/curator/minter_service.rb) should make an API call to the ark-manager application to request a new ARK identifier.

The `@namespace` value will need to dependent on the environment -- dev (`bpl-dev`), staging (`bpl-test`, or production (`commonwealth`), though the ark-manager will likely already take this into account.

This is somewhat blocked by #9, since the new version of the ark-manager will likely have a different API request syntax.

**Comment by bbarberBPL** [comment]
Unblocked since issue #9 is now closed
