### ISSUE TITLE
Implement a simple lightweight API that caches authority data 

### ISSUE THREAD

**Issue by bbarberBPL** [boston-library/curator#6]
See the following implementations that utilize the [Questioning Authority Gem](https://github.com/samvera/questioning_authority) 

[QA Server 1](https://github.com/cul-it/qa_server)
[QA Server 2](https://github.com/LD4P/qa_server)

Also revisit the [BPL Encrich Gem](https://github.com/boston-library/bpl_enrichl) to update and leverage QA gem.  

This will tie in with our controlled terms so we can fetch data from this API on create to get any missing or updated data from the source.  We can also leverage caching to ensure fast responses during ingests. 

Plus we can also use it to serve data for autocomplete functionality on the new admin side.

**Comment by ebenenglish** [comment]
This functionality will be handled by [bpldc_authority_api](https://github.com/boston-library/bpldc_authority_api). Any additional ideas for this service should be added as issues on that repo.
