### ISSUE TITLE
licenses should be a has_one relationship

### ISSUE THREAD

**Issue by ebenenglish** [boston-library/curator#64]
After review with the metadata team, we do not need to support adding multiple licenses for objects.

So, we can change the relationship for `Metastreams::Descriptive` like so:
```
has_one :licenses, class_name: 'Curator::ControlledTerms::License'
```

**Comment by bbarberBPL** [comment]
Will actually make this a `belongs_to` and directly map to descriptive object similar to how `physical_location` is
