### ISSUE TITLE
Soft Deletion(Archivable)

### ISSUE THREAD

**Issue by bbarberBPL** [boston-library/curator#7]
All models(except for the ones in the mapping scope) have `datetime` field called `archived_at`. There are gems out there that implement soft deletes such as `paranoia` but rather than add yet another dependency we should be able to implement this ourselves. Also we shouldn't use a default scope for these instead we should check scope the records by user type. I started implementing this in the project but it needs to be implemented and tested out before use.

**Comment by ebenenglish** [comment]
Setting this as low priority for now. This feature isn't currently available in the existing repository, so this is not needed for feature parity.

Good discussion of the complexity this adds here:
https://medium.com/galvanize/soft-deletion-is-actually-pretty-hard-cb434e24825c

**Comment by bbarberBPL** [comment]
Closing this due to the implementation of paper trail. Removed all references to this in #355
