### ISSUE TITLE
Perform Health Check on Solr service before indexer is invoked in callback

### ISSUE THREAD

**Issue by bbarberBPL** [boston-library/curator#75]
Right now if you create an object in the database the record indexer is invoked in an `after_commit` callback. This is fine except if the Solr service becomes unresponsive. Ideally we should do a health check before the record is committed but after is is saved (either in a `after_save` or `around_save` callback. Also see callback order defined [here](https://guides.rubyonrails.org/active_record_callbacks.html#available-callbacks) ). If the health check fails we should either raise an `ActiveRecord::Rollback` error or schedule a background job to re run the indexer(this relates to #17 ).

**Comment by ebenenglish** [comment]
Add a method to `Curator::SolrUtil` along the lines of:
```
def self.solr_ready?
  rsolr = RSolr.connect
  begin
    ping_request = rsolr.head('admin/ping')
    ping_request&.response[:status] == 200 ? true : false
  rescue => e
    puts "ERROR: Solr is not ready: #{e}"
    return false
  end
end
```
