### ISSUE TITLE
Add `file_set_type` inside to json files related to actual file objects in export script.

### ISSUE THREAD

**Issue by bbarberBPL** [boston-library/curator#76]
Given the json structure below the `file_set_type` key needs to be added nested inside the `file_stream_of` hash. Note that it should correspond the the child classes of `Curator::Filestreams::FileSets`

```
{
  "file": {
     ...
    "filestream_of": {
      "ark_id": "commonwealth:000000000"
      "file_set_type": "image"
    }
  }
}

```

**Comment by ebenenglish** [comment]
Fixed via https://github.com/boston-library/bplmodels/commit/b8491174510079ab9df0d6cae744d0de41b68a0a
